### ISSUE TITLE
Unable to load pickle files in python 3

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#120]
When trying to call the function `pickle.load` function from **python 3** in  a [model files](https://github.com/MD-Studio/MDStudio/blob/master/scripts/1A2_model/params.pkl) stored with **python 2**,
I got the following error:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 0: ordinal not in range(128)
```

**Comment by marcvdijk** [comment]
Unpickling a python 2.x pickle in 3.x is for sure not going to work here
