### ISSUE TITLE
Redis docker THP warning on OSX 10.11.6

### ISSUE THREAD

**Issue by marcvdijk** [MD-Studio/MDStudio#125]
Following warning from the redis docker log on Mac OSX 10.11.6:

60:M 03 May 06:22:50.561 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

**Comment by PaulVisscher** [comment]
This is a warning that we cannot easily fix, see https://github.com/docker-library/redis/issues/55 . I don't think that it matters on development builds, and on production you should have a separate redis cluster anyway.
