### ISSUE TITLE
create ansible playbook

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#135]
Generate an [ansible playbook](https://docs.ansible.com/ansible/latest/index.html) to install all the dependencies in a host.

**Comment by marcvdijk** [comment]
He Felipe,

Is there a need for this? My previous experiences with Ansible where not that good. Keep it simple and avoid yet another package if possible I would say.

Cheers,

Marc

**Comment by felipeZ** [comment]
I would use to install docker and other dependencies for development. I will not be part of the standard installation, just for testing and development.
