### ISSUE TITLE
standalone.sh not working

### ISSUE THREAD

**Issue by LourensVeen** [MD-Studio/MDStudio#149]
There's a link to a directory on Marc's laptop in ./standalone.sh, at least in the devel branch. I don't have that directory, so it doesn't work.

Also, I don't have `/opt/local/bin/python3.6` or `/opt/local/bin/python2.7`. On Ubuntu 16.04 (yes, I should upgrade, soon...) these are `/usr/bin/python3.5` and `/usr/bin/python2.7`. If 3.5 is enough, maybe we could get away with just using `python3` and `python2`, instead of specifying the second number?

I'm trying to run inside of a virtualenv, but that doesn't seem to work either. I'm stuck at `data/home/lourens/Envs/MDStudio/bin/python: No module named lie_md` now...

**Comment by marcvdijk** [comment]
Fixed in https://github.com/MD-Studio/MDStudio/commit/bf4c3bee70ebfeb3904f3f6370ad75b1b5e3850d
