### ISSUE TITLE
Use isinstance of the type function

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#23]
In Python is not recommend to check the type of an object directly instead
it is recommend to use the `isinstance` function.

See: [official docs](https://docs.python.org/2/library/types.html) and [blog](https://blog.duraffort.fr/post/2016/05/03/type-vs-isinstance/)

**Comment by felipeZ** [comment]
there are several expressions of the form:
```
 if type(foo) in (str, unicode):
```

A more pythonic way for this expressions is to use the [six](library) and
replace those expressions by
```
isinstance(foo, six.text_type)
```
The `six.text_type` expression takes care to check whether is `str` in python3 or `unicode` in python2

**Comment by marcvdijk** [comment]
I'm aware of that.
Better would even be to have everything in unicode as with Python 3. Also fits better with WAMP and JSON usage

**Comment by PaulVisscher** [comment]
#37  fixes this for core components.
