### ISSUE TITLE
Phusion Docker image vs standard linux image

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#27]
As far as I understand there are mainly 3 reason to use a `phusion` image instead of a standard linux image (or python image):
*  You need to run multiple processes. Even though Docker recommends a single application per container.
*  You need the [cron](https://en.wikipedia.org/wiki/Cron) command.
* You want to connect to the container through a SSH protocol. In other words, do we have any procedure that we can not handle using `docker exec` ?

**Comment by felipeZ** [comment]
Here is an interesting discussion about [SSH in docker](https://news.ycombinator.com/item?id=7951042)

**Comment by PaulVisscher** [comment]
#37 uses the default python docker images and ssh is disabled in the images.
