### ISSUE TITLE
pybabel causing random errors

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#29]
There is a [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862517) in some linux openbabel installation that cause an import error like:
```python
  File "/path/venv/local/lib/python2.7/site-packages/pybel.py", line 84, in _getpluginnames
    return [x.split()[0] for x in plugins]
exceptions.IndexError: list index out of range
```
There is no much that we can do, but at least we should be aware of it.
If this error is raised the only alternative is to kill the process and try to restart.

**Comment by marcvdijk** [comment]
should be fixed with the move to the newer Cinfony environment in the lie_structures module.
At least unit tests pass.
