### ISSUE TITLE
Improve lie_md module

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#32]
apart from the WAMP functionality, all the modules in [lie_md](https://github.com/MD-Studio/MDStudio/tree/master/components/lie_md/lie_md) need to be restructured or complete rewritten from scratch.

**Comment by felipeZ** [comment]
This is what flycheck says about the [gromacs_topology_amber.py](https://github.com/MD-Studio/MDStudio/blob/master/components/lie_md/lie_md/gromacs_topology_amber.py) module:

> Warning (flycheck): Syntax checker python-flake8 reported too many errors (499) and is disabled.

**Comment by marcvdijk** [comment]
I agree on that. This is code I copied from the eTOX ALLIES project. It has been written many years ago. Can't even remember by whom. It is in lie_md to make the MVP work. Later on, the functionality will probably be replaced by the module Koen is writing.

**Comment by felipeZ** [comment]
fixed by #67
