### ISSUE TITLE
Json files size

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#33]
in [WAMP](http://wamp-proto.org/) the data between [RPCs](http://wamp-proto.org/faq/#rpc) calls are transfer using **JSON**, when we start passing large string containing proteins (> 1MB), the system fails and crashes with errors difficult to track. 
Instead of passing whole proteins encoded as strings we should pass absolute paths to the molecule files.

**Comment by marcvdijk** [comment]
I agree that passing file paths is a good idea for multiple reasons as long as the files are on the same storage location or shared through some sort of distributed storage API. However, I don't think that the JSON message size itself is much of a problem. WebSockets are able to handle large data chunks. The problem that you are experiencing might be related to the UTF encoding I mentioned previously.

**Comment by PaulVisscher** [comment]
This issue basically addresses an other issue we are currently facing: "What should we do with large files?"

I am closing this issue in favour of #41.
